### PR TITLE
[BLOCKED] Standard vcf

### PR DESCRIPTION
**Pull request by yunfeiguo**
- [x] [RES-444](https://binatechnologies.atlassian.net/browse/RES-444)
- [x] Blocking PRs: #66 
* People
  - [x] Reviewers (>=1): @marghoob 
  - [x] Merger (>=1): @marghoob 
  - [x] FYI: @msahraeian, @ulitskyb
- [x] Release note (if needed)
- [x] No code copied from outside Bina 
- [x] Tests (Unit, Workflow, ITL & Gherkin) are passing
- [x] PR labels, milestones & assignees

# Summary

* standardize translocation and interspersed duplication representation
* each translocation is representated as a deletion `<DEL:TRA>` and a duplication `<DUP:TRA>`
* `<DUP:ISP>` denotes an interspersed duplication (one reference sequence is copied and pasted somewhere in the genome other than its original locus).
* some additional variant types/flexseq types were created to accommodate these changes
* test files were modified to reflect changes in header/variant representation.

### CODE REVIEW

**Comment by yunfeiguo** [comment]
@marghoob all changes are done. Thanks!

**Comment by marghoob** [comment]
Could you merge master to this branch to ensure the diff is right.

**Comment by yunfeiguo** [comment]
Sure.

**Comment by yunfeiguo** [comment]
Thanks.

**Pull request merged**
