### PR TITLE
refactor

### PR DESCRIPTION
**Pull request by yunfeiguo**
- [x] [RES-512](https://binatechnologies.atlassian.net/browse/RES-512)
- [x] Blocking PRs: ADD HERE IF ANY
* People
  - [x] Reviewers (>=1): @marghoob 
  - [x] Merger (>=1): @marghoob 
  - [x] FYI: ADD HERE IF ANY
- [x] Release note (if needed)
- [x] No code copied from outside Bina 
- [x] Tests (Unit, Workflow, ITL & Gherkin) are passing
- [x] PR labels, milestones & assignees

# Summary

refactor code in VCFCompare and VCFParser to reduce redundancy and improve maintainability.

### CODE REVIEW

**Comment by marghoob** [comment]
Please do not forget to merge master in to this one.

**Comment by yunfeiguo** [comment]
Sure. Thanks.

**Comment by yunfeiguo** [comment]
@marghoob , could you please take a look at the changes I made? Especially `public int compareVariant(Variant variant, int genotype, BitSet validated)`, I deleted quite a few potentially redundant if statements. Thanks.

**Comment by marghoob** [comment]
@yunfeiguo can you please merge master in this and remove the conflicts?

**Comment by yunfeiguo** [comment]
@marghoob , done, thanks!

**Pull request merged**
